worker_processes 1;

error_log D:/FASTAPI/server-Frontend/nginx/logs/error.log;
pid D:/FASTAPI/server-Frontend/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include D:/FASTAPI/server-Frontend/nginx/conf.d/*.conf;
    include D:/FASTAPI/server-Frontend/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    access_log D:/FASTAPI/server-Frontend/nginx/logs/access.log;
}
